package com.bhagwat.scm.paymentService.entity;

import com.bhagwat.scm.paymentService.common.PaymentMethod;
import com.bhagwat.scm.paymentService.common.TransactionStatus;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Persistent record for every payment initiated through the Cashfree gateway.
 *
 * This table is the authoritative audit log. Each row is created when the client
 * calls /gateway/initiate and updated on every status transition (Cashfree order
 * creation, webhook arrival, status poll reconciliation).
 */
@Entity
@Table(
    name = "payment_transactions",
    indexes = {
        @Index(name = "idx_pt_order_id",        columnList = "orderId"),
        @Index(name = "idx_pt_cf_order_id",     columnList = "cfOrderId"),
        @Index(name = "idx_pt_debitor_id",      columnList = "debitorId"),
        @Index(name = "idx_pt_status",          columnList = "status"),
        @Index(name = "idx_pt_idempotency_key", columnList = "idempotencyKey", unique = true)
    }
)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentTransaction {

    // ── Identity ───────────────────────────────────────────────────────────────

    @Id
    @Column(length = 36)
    private String transactionId;          // UUID generated by us

    @Column(nullable = false, length = 50)
    private String orderId;                // Caller-supplied order reference

    @Column(length = 50, unique = true)
    private String idempotencyKey;         // Deduplication key (defaults to orderId)

    // ── Cashfree identifiers ───────────────────────────────────────────────────

    @Column(length = 50)
    private String cfOrderId;             // Cashfree's cf_order_id

    @Column(length = 255)
    private String paymentSessionId;      // Cashfree payment_session_id

    @Column(length = 255)
    private String cfPaymentId;           // Cashfree's individual payment ID (from webhook)

    @Column(length = 100)
    private String bankReference;         // Bank reference from successful payment

    // ── Debitor (payer) ────────────────────────────────────────────────────────

    @Column(nullable = false, length = 100)
    private String debitorId;

    @Column(length = 200)
    private String debitorName;

    @Column(length = 200)
    private String debitorEmail;

    @Column(length = 20)
    private String debitorPhone;

    // ── Creditor (payee) ───────────────────────────────────────────────────────

    @Column(nullable = false, length = 100)
    private String creditorId;

    @Column(length = 200)
    private String creditorName;

    @Column(length = 30)
    private String creditorAccount;

    @Column(length = 20)
    private String creditorIfsc;

    // ── Payment details ────────────────────────────────────────────────────────

    @Column(nullable = false, precision = 15, scale = 2)
    private BigDecimal amount;

    @Column(length = 3)
    @Builder.Default
    private String currency = "INR";

    @Enumerated(EnumType.STRING)
    @Column(length = 20)
    private PaymentMethod paymentMethod;

    // ── Status ─────────────────────────────────────────────────────────────────

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private TransactionStatus status;

    /** Raw status string from Cashfree order API (ACTIVE, PAID, EXPIRED, …). */
    @Column(length = 30)
    private String gatewayOrderStatus;

    /** Raw status string from Cashfree payment (SUCCESS, FAILED, USER_DROPPED, …). */
    @Column(length = 30)
    private String gatewayPaymentStatus;

    /** Failure reason or gateway error message if status is FAILED. */
    @Column(length = 500)
    private String failureReason;

    // ── Checkout URL ───────────────────────────────────────────────────────────

    /** Hosted checkout URL sent to the client after order creation. */
    @Column(length = 500)
    private String paymentLink;

    /** ISO-8601 string for order expiry time from Cashfree. */
    @Column(length = 50)
    private String orderExpiryTime;

    // ── Webhook tracking ───────────────────────────────────────────────────────

    /** Whether a webhook has been received for this transaction. */
    @Column(nullable = false)
    @Builder.Default
    private boolean webhookReceived = false;

    @Column(length = 50)
    private String webhookEventType;

    // ── Timestamps ─────────────────────────────────────────────────────────────

    @Column(nullable = false, updatable = false)
    private LocalDateTime initiatedAt;

    @UpdateTimestamp
    private LocalDateTime updatedAt;

    /** For optimistic locking — prevents double-update race on webhooks. */
    @Version
    private Long version;

    @PrePersist
    private void onPersist() {
        if (initiatedAt == null) initiatedAt = LocalDateTime.now();
        if (status == null) status = TransactionStatus.INITIATED;
    }
}
