package com.bhagwat.scm.paymentService.entity.wallet;

import com.bhagwat.scm.paymentService.common.WalletStatus;
import com.bhagwat.scm.paymentService.common.WalletType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.UpdateTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Wallet owned by an organisation (orgId only) or one of its divisions (orgId + divisionId).
 *
 * Uniqueness: the combination (orgId, divisionId) must be unique.
 * When divisionId is null, the wallet belongs to the organisation as a whole.
 *
 * Balance integrity:
 *   - All mutations go through {@code WalletBalanceService} which uses optimistic locking.
 *   - Never update {@code balance} directly outside of that service.
 */
@Entity
@Table(
    name = "enterprise_wallets",
    uniqueConstraints = @UniqueConstraint(
        name  = "uq_enterprise_wallet_org_div",
        columnNames = {"org_id", "division_id"}
    ),
    indexes = {
        @Index(name = "idx_ew_org_id",   columnList = "org_id"),
        @Index(name = "idx_ew_status",   columnList = "status")
    }
)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class EnterpriseWallet {

    @Id
    @Column(length = 36)
    private String walletId;                    // UUID — generated by service

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20, updatable = false)
    @Builder.Default
    private WalletType walletType = WalletType.ENTERPRISE;

    @Column(name = "org_id", nullable = false, length = 100)
    private String orgId;

    /** Null = org-level wallet. Non-null = division-level wallet. */
    @Column(name = "division_id", length = 100)
    private String divisionId;

    @Column(nullable = false, length = 200)
    private String walletName;

    /** Current available balance — never negative. */
    @Column(nullable = false, precision = 18, scale = 2)
    @Builder.Default
    private BigDecimal balance = BigDecimal.ZERO;

    /** ISO 4217 currency code. */
    @Column(nullable = false, length = 3)
    @Builder.Default
    private String currency = "INR";

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    @Builder.Default
    private WalletStatus status = WalletStatus.ACTIVE;

    /** Created by (userId / system identifier). */
    @Column(length = 100, updatable = false)
    private String createdBy;

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    private LocalDateTime updatedAt;

    /** Optimistic locking — prevents concurrent balance races. */
    @Version
    private Long version;

    @PrePersist
    private void onPersist() {
        if (createdAt == null) createdAt = LocalDateTime.now();
    }
}
